import type { Metadata } from "next";
import Nav from "@/app/Components/Layout/Nav";
import Footer from "@/app/Components/Layout/Footer";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
       <Nav/>
        {children}
       <Footer/>
      </body>
    </html>
  );
}
