import type { Metadata } from "next";
import Nav from "@/app/[locale]/Components/Layout/Nav";
import Footer from "@/app/[locale]/Components/Layout/Footer";
import {useTranslations} from 'next-intl';
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
    const lang = useTranslations('Index')('lang');
    const dir = useTranslations('Index')('dir');
    return (
    <html className='scroll-smooth' lang={lang} dir={dir}>
      <body>
       <Nav/>
        {children}
       <Footer/>
      </body>
    </html>
  );
}
