import { NextIntlClientProvider} from 'next-intl';
import {getMessages} from 'next-intl/server';
import type { Metadata } from "next";
import Nav from "@/app/[locale]/Components/Layout/Nav";
import Footer from "@/app/[locale]/Components/Layout/Footer";
import "./globals.css";


export const metadata: Metadata = {
    title: "ctihc",
    description: "Holding Company for Cotton and Textiles",
};

export default async function RootLayout({
              children,
              params: {locale}
       }: {
    children: React.ReactNode;
    params: {locale: string};
}) {
    // Providing all messages to the client
    // side is the easiest way to get started
    const messages = await getMessages();
    return (
        <html lang={locale} dir={locale === 'en' ? 'ltr' : 'rtl'}>
        <body>
        <NextIntlClientProvider messages={messages}>
            <body>
              <Nav/>
               {children}
             <Footer/>
            </body>
        </NextIntlClientProvider>
        </body>
        </html>
    );
}

/*
import type { Metadata } from "next";
import Nav from "@/app/[locale]/Components/Layout/Nav";
import Footer from "@/app/[locale]/Components/Layout/Footer";
import {useTranslations} from 'next-intl';
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
    const lang = useTranslations('Index')('lang');
    const dir = useTranslations('Index')('dir');
    return (
    <html className='scroll-smooth' lang={lang} dir={dir}>
      <body>
       <Nav/>
        {children}
       <Footer/>
      </body>
    </html>
  );
}
*/
